# Generated by Django 2.2 on 2022-08-08 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='end_data_pay',
            field=models.DateField(blank=True, default=datetime.date(2023, 8, 8), null=True),
        ),
    ]
