# Generated by Django 2.2 on 2022-08-09 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20220808_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='end_data_pay',
            field=models.DateField(blank=True, default=datetime.date(2023, 8, 9), null=True),
        ),
    ]
