# Generated by Django 2.2 on 2022-08-10 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20220809_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='end_data_pay',
            field=models.DateField(blank=True, default=datetime.date(2023, 8, 10), null=True),
        ),
    ]
