# Generated by Django 2.2 on 2022-07-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RomEngExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romex', models.CharField(max_length=100)),
                ('engex', models.CharField(max_length=100)),
            ],
        ),
    ]
