# Generated by Django 2.2 on 2022-08-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_romengexp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngRomVerbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=100)),
                ('engdict', models.CharField(max_length=100)),
                ('rom', models.CharField(max_length=100)),
            ],
        ),
    ]
