# Generated by Django 2.2 on 2022-08-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_engromverbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='WayToSay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rom', models.CharField(max_length=300)),
                ('eng', models.CharField(max_length=300)),
            ],
        ),
    ]
